### ISSUE TITLE
android:theme="@style/Theme.Transparent" problem

### ISSUE THREAD

**Issue by eRistocracy** [myflashlab/inAppPayments-ANE#1]
Hi. I can't compile my game with your Billing ANE. It has some props with the theme:

![billingerror](https://cloud.githubusercontent.com/assets/2574012/12870109/b2857ed2-cd35-11e5-965b-4225ce236fd3.jpg)

**Comment by myflashlab** [comment]
considering that the theme resource is already there in the ANE, it's probable that something else has caused the aapt fail and in result it was not able to find the resources. here is a check list:

1. are you using the latest Air SDK version?

2. we have never used intellij IDE for compiling Air apps, but if the IDE is requiring you to use Android SDK path, please make sure you have updated your Android SDK.
3. Are you using other ANEs from other providers? if yes, try to disable them first and then run your project to see if you are still facing the error message? then add them one by one to see which one is causing the possible conflict.

**Comment by eRistocracy** [comment]
Sorry for the late reply, but I managed to connect your inApp ANE and I just started implementing it, but I had to disconnect Distriqt Ads ANE (AdMob) (with their GameServices), because you don't have one. I would be very happy if I could fully rely on you as an ANE provider ;)

It can also be something on my side, but I will investigate it and let you know if I find something sure.

Anyway... keep your awesome work rollin and have a nice day (probably night) ;D

**Comment by myflashlab** [comment]
yes, sure :) we are actually working on the game center ANE and ad ANEs. they will be ready soon.

**Comment by eRistocracy** [comment]
How long do you think it might take you? I have just prolonged this Distriqt ANE, but I would love to drop it completely and stick with your "factory" ;)

**Comment by myflashlab** [comment]
don't have a date currently as the game center ANE is HUUGE and requires a lot of work/time. We'll have them all eventually!

**Comment by eRistocracy** [comment]
Ok. I will be waiting... and I bet I am not the only one ;)

Thanks for your feedback. I will let you know if I find something.

Kind regards
Kuba
