### ISSUE TITLE
I have problems with debug on ANDROID

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/inAppPayments-ANE#11]
I added 3 in-app products to Google Play:
http://prntscr.com/b5zllg

I send array of products
http://prntscr.com/b5zmlx

I used Android Key from there
http://prntscr.com/b5zn6p

I have app in game services - READY TO TEST
http://prntscr.com/b5zqlp 

It is all in debug mode `Billing.IS_DEBUG_MODE = true;`

But I received message: "No product match found on server!"

What do I wrong?

P.S. On iOs works great!

**Comment by TillSimon** [comment]
Same thing here. With debug on or off, I get that error message. I published the item 20 hours ago, so its not that its not propagated globally yet.
I want to buy the full ANE, but obviously need to make sure that its working properly.
Help appreciated!

**Comment by myflashlab** [comment]
There could be many reasons why it's not working and you would probably find a solution by some Googling. but below are just some tips which you may hopefully find helpful:

first make sure you have read the following notes:
https://github.com/myflashlab/inAppPayments-ANE/blob/master/FD/src/MainFinal.as#L230-L236

then, make sure you have correctly setup your manifest .xml file. You can [check here](https://github.com/myflashlab/inAppPayments-ANE#air-xml-manifest) for the correct setup.

**Comment by myflashlab** [comment]
@Gamezhero setting the Google Games Services has nothing to do with setting up the in-app-billing in Android! please do not confuse these with each other. if you want to know more about Google Games Services ANE, you should read this Wiki here https://github.com/myflashlab/GameServices-ANE/wiki

**Comment by TillSimon** [comment]
From what I remembered from previous projects the app could stay in a draft/unpublished state to test IAPs. Turns out it needs to be published (e.g. to alpha testing).
@Gamezhero this also seems to be the issue in your case (thanks Google Translate) :)

@myflashlab Thanks heaps for your help though

**Comment by myflashlab** [comment]
@TillSimon yes, must be published to alpha or beta testing at least. This is the new requirements.

@Gamezhero If all is fine, please let us know. And if you have more questions, feel free to ask.

**Comment by Gamezhero** [comment]
I publish game in alpha testing and got product list (android), 
but can't buy in debug mode, I see error:

Error This product is not for sale (google translate)

**Comment by TillSimon** [comment]
@Gamezhero You need to add your device's account email address to the alpha/beta testing group. When creating the new list of testers, also make sure you check it as 'active' !
Then open https://play.google.com/apps/testing/[package name]/join with the respective google account and join as a tester.
Make sure that account is not your play developer account.
You might have to wait until testers are propagated across google servers...
I also installed the app via google play with the tester account and not the apk manually...don't know if thats necessary.

**Comment by TillSimon** [comment]
@myflashlab Any reason why Billing.init can't be called again after it failed once? If the user is offline on the first launch of the app, I might not be able to init and fetch products. But when he tries to buy something/upgrade, I need to be able to try again to init the lib. This is crucial to potential revenue.. And it certainly wouldnt be good UX to tell the user to please restart the app..

**Comment by myflashlab** [comment]
@TillSimon  is this happening on Android or iOS or both? and have you tried ```Billing.dispose();``` before re-initializing the ANE?

**Comment by myflashlab** [comment]
> I also installed the app via google play with the tester account and not the apk manually...don't know if thats necessary.

No, it's not necessary. it should work with locally installed .apk also.

**Comment by myflashlab** [comment]
@Gamezhero Please let us know if what @TillSimon suggested helped you? Those are valid statements.

**Comment by TillSimon** [comment]
@myflashlab Ah thank you, `Billing.dispose();` worked. Sorry, didn't see that one. I'm only working with Android atm, so can't say for iOS...
And yes, everything also works with the local apk-install.
