### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by Diamanter** [myflashlab/inAppPayments-ANE#12]
It crashes on init();

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count: ]: attempt to insert nil object from objects[0]'

Billing.init("MIIBIjA...", itemArr, itemArr, onBillingInit); // itemArr is not empty

AIR 22.0, iOS 9.3.2, ANE 2.0.0

I can send my ipa if you need.

**Comment by myflashlab** [comment]
The ```itemArr``` must be an Array containing Strings and each String will be your product ID that you created in your Google Play console or your itunes connect console.

**Comment by Diamanter** [comment]
Yes, here is my array:

private var itemArr:Array = 
["air.com.rentabiliweb.sushiquest.skiplevel", 
"air.com.rentabiliweb.sushiquest.unlimlives", 
"air.com.rentabiliweb.sushiquest.10lives", 
"air.com.rentabiliweb.sushiquest.25lives", 
"air.com.rentabiliweb.sushiquest.150coins", 
"air.com.rentabiliweb.sushiquest.50coins", 
"air.com.rentabiliweb.sushiquest.10coins"];

I added them in Apple in app purchases already.

One subtle: my app is not approved yet, so my in app purchases are not 
approved yet. I need a working ipa to pass an approve. What can I do?

Denis.

25.05.2016 10:35, myflashlab пишет:

**Comment by myflashlab** [comment]
Quick guess, you're running this on a real device, right? Because it won't
work on a simulator. Please confirm that.

On Wednesday, May 25, 2016, Denis V. Chumakov <notifications@github.com>
wrote:

> Yes, here is my array:
>
> private var itemArr:Array =
> ["air.com.rentabiliweb.sushiquest.skiplevel",
> "air.com.rentabiliweb.sushiquest.unlimlives",
> "air.com.rentabiliweb.sushiquest.10lives",
> "air.com.rentabiliweb.sushiquest.25lives",
> "air.com.rentabiliweb.sushiquest.150coins",
> "air.com.rentabiliweb.sushiquest.50coins",
> "air.com.rentabiliweb.sushiquest.10coins"];
>
> I added them in Apple in app purchases already.
>
> One subtle: my app is not approved yet, so my in app purchases are not
> approved yet. I need a working ipa to pass an approve. What can I do?
>
> Denis.
>
> 25.05.2016 10:35, myflashlab пишет:
> >
> > The |itemArr| must be an Array containing Strings and each String will
> > be your product ID that you created in your Google Play console or
> > your itunes connect console.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/myflashlab/inAppPayments-ANE/issues/12#issuecomment-221477516
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/inAppPayments-ANE/issues/12#issuecomment-221485625>
>


-- 
Sent from iPhone

**Comment by Diamanter** [comment]
Yes, running on iPhone 5s, ipa-debug and ipa-app-store, in Sandbox mode 
(same as Apple approvers). I tried
Billing.IS_DEBUG_MODE = true; and =false. Same crash.

Denis.

25.05.2016 12:02, myflashlab пишет:

**Comment by vulkanosaure** [comment]
Seriously ? 19 days and no answer, it really dont make me want to spend money there...

**Comment by Diamanter** [comment]
Switched to Milkaman already. But I can try again later if they can fix this )

**Comment by myflashlab** [comment]
We're not sure what could be the reason of the crash as we cannot reproduce the bug! If you can help us reproduce it, we will be able to fix it. 

Leaving notes like you are switching or such is not motivating nor helpful!

**Comment by myflashlab** [comment]
try sending two different ```itemArr``` to that method and see how it goes.

```actionscript
Billing.init("MIIBIjA...", itemArr, itemArr, onBillingInit); // itemArr is not empty
```

**Comment by Diamanter** [comment]
I told you "I can send my ipa if you need." (see above). It reproduced the bug 100%.

After 2 weeks of silence I switched to other ANE of course, wait I will try your ane in other application.

I can't try "Billing.init(..." already, but I remebered it.

**Comment by myflashlab** [comment]
Having just the .ipa file is good but not helpful enough. the best way to reproduce a bug is to see a demo app demonstrating the problem. anyway, try the suggestion I mentioned in my last post.
