### ISSUE TITLE
onInitComplete is never called if no internet connection

### ISSUE THREAD

**Issue by serjek** [myflashlab/inAppPayments-ANE#13]
Billing init is never completed if device is lacking internet connection. To verify just debug the ANE on device with "plane" mode on:
```
Billing.IS_DEBUG_MODE = true;
Billing.init(LICENCE,PRODUCTS,PRODUCTS,initComplete);
```

initComplete is expected to be called, but actually it is not the case.

Tested on iOS device.

**Comment by myflashlab** [comment]
https://github.com/myflashlab/inAppPayments-ANE/issues/14
