### ISSUE TITLE
How would I access cached purchase data?

### ISSUE THREAD

**Issue by serjek** [myflashlab/inAppPayments-ANE#14]
I need to access local cache of purchase data ANE has created. This is useful for cases when user does not have the internet connection and still want to use permanent in-app products he purchased before.

Also, when does this local cache populate? Does this happen only on Billing.doPayment call or this also happens when Billing.getPurchases is called as well? Reason I ask is for following case: say, user did install the app, purchased permanent in-app product, then uninstalled the app. Once he installs the app again we call Billing.getPurchases and it would be nice to have local cache populated at this point for case described above (when user is about to use the product but does not have the internet connection).

**Comment by serjek** [comment]
Thing is, when I call Billing.getPurchases if no internet connection, I expect to get cached purchases, but I get the "No product match found on server" error instead. Perhaps this could be related to issue #13 I submitted recently?

**Comment by myflashlab** [comment]
We are aware of this issue and we are preparing for a new release. Thanks.

**Comment by hpeide** [comment]
Any progress on this?

**Comment by myflashlab** [comment]
Guys, do you have this problem on Android or iOS? The latest version of the ANE will return purchase data if it is already saved in cached database. Let us know if you are experiencing something else?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
