### ISSUE TITLE
Can't get code to work

### ISSUE THREAD

**Issue by blayza** [myflashlab/inAppPayments-ANE#16]
Hi, I bought the ANE a few days ago. However, so far my developer has been having trouble getting it to work. He is getting an error message due to some methods which we call in the ane not being defined in ane. The developer has checked methods called in my code in the api list in html file
in the doc section

I'm using latest version of animate. 
So far we are just working on ios iap, so I can't comment on whether the problem exists for android.

The app compiles ok onto my ipad, and besides IAP function, the code works fine.

When you click Restore purchases, user is prompted to enter itunes password, but this is not accepted even when it is entered correctly.

And buy now doesn't work. The coder is stumped, and looking for guidance.

Code we are using in the app is below. Any help much appreciated. 

Thanks,
Leon 

//iap code
import com.myflashlab.air.extensions.billing.Billing;
import com.myflashlab.air.extensions.billing.BillingType;
import com.myflashlab.air.extensions.billing.Purchase;
import com.myflashlab.air.extensions.billing.Product;
import com.InAppManager;
import flash.events.Event;

var inAppManager:InAppManager = new InAppManager(this);
InAppManager.inAppManager = inAppManager;

this.addEventListener( InAppManager.BUY_NOW, buyNowHandler );
this.addEventListener( InAppManager.RESTORE_PURCHASE, restorePurchasesHandler );

function buyNowHandler( p_evt:Event ):void {
	inAppManager.buyNow();
}

function restorePurchasesHandler( p_evt:Event ):void {
	inAppManager.getPurchases();
}

**Comment by myflashlab** [comment]
Could you please post the error message you are receiving?

I'm guessing that you are running the ANE on a simulator, if so, try running it on a real device. the following issues may help you:
https://github.com/myflashlab/inAppPayments-ANE/issues/7  
https://github.com/myflashlab/inAppPayments-ANE/issues/10

**Comment by blayza** [comment]
Basically.... referenced your suggestions, and tried to find errors in the code. We thought we'd cracked it, but no... current situation is still that the app itself runs fine, but IAP unlock process is not working.

On click, I am asked for apple id and password, but it tells me "The Apple ID you entered couldn't be found or password was incorrect. Please try again".

**Comment by myflashlab** [comment]
Can you confirm if you are entering your test/fake apple id information or your real apple id?

Please note that when you are in developing phase, you need to create a fake Apple ID from your iTunes connect panel. Here find more information: https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/TestingInAppPurchases.html

**Comment by blayza** [comment]
Yes, I can confirm that that works! Thanks for the quick reply.

**Comment by myflashlab** [comment]
I'm not sure I understood if the problem is now solved after using a test user? Or you still have trouble with it?

**Comment by blayza** [comment]
Yes, it was fixed!
