### ISSUE TITLE
 In App BIlling v3 doesn't work

### ISSUE THREAD

**Issue by MyMyGames** [myflashlab/inAppPayments-ANE#17]
Problem setting up in-app billing: error checking for billing v3 support. (response: 3: billing unavailable) 
Does anyone know anything about this?

P.S. This happens on different devices which have completely separate user accounts.

**Comment by myflashlab** [comment]
There might be many reasons for that! one of them could be that you don't have Google Play app on your device. other one could be that you are not logged in to a google account on your device. Or maybe you have not setup the ANE/manifest correctly?

**Comment by myflashlab** [comment]
Please let us know how it goes? If you have any questions, do ask.

**Comment by leossmith** [comment]
I also have trouble with this. I event waited a couple of days for google but still nothing. I have also tried pushing the version to production to see if it makes any difference, but i just won't initialize on debug.

**Comment by myflashlab** [comment]
Setting up the properties of the in-app-billing is usually very tricky. Let's run your sample app on the given FlashDevelop sample project we have here and see what results you are seeing?

Another thing that might help is to send us logcat debug log. Maybe there we can find some helpful information about what could have been missed in your setup.

**Comment by leossmith** [comment]
So after testing a few things, it looks like it works perfectly on iOS but can't figure out why on android debug i get "no products".
