### ISSUE TITLE
just purchase commercial liscense 

### ISSUE THREAD

**Issue by khurramkhanmr** [myflashlab/inAppPayments-ANE#18]
Hi team, 

I am trying to configure .ane or .swc but still no success or initialize 

Error:
at com.myflashlab.air.extensions.billing::Launcher()
	at com.myflashlab.air.extensions.billing.android::Android()
	at com.myflashlab.air.extensions.billing::Billing()
	at com.myflashlab.air.extensions.billing::Billing$/init()
	at v3_fla::MainTimeline/frame1()[v3_fla.MainTimeline::frame1:21]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by khurramkhanmr** [comment]
WF] v3.swf - 3734 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at Function/<anonymous>()
	at Function/http://adobe.com/AS3/2006/builtin::apply()
	at SetIntervalTimer/onTimer()
	at flash.utils::Timer/_timerDispatch()
	at flash.utils::Timer/tick()

**Comment by khurramkhanmr** [comment]
in the package I have got inAppPayments.ane or inAppPayments.swc , I am using .ane for my android app. please advise. I have added .ane from the publish setting FlashCC

**Comment by myflashlab** [comment]
The error message shows you have not embeded the ANE correctly. Please watch these videos: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by khurramkhanmr** [comment]
Thanks for your feedback . yes I followed the method used to import .ane 

Please see the attached image
![inapp error](https://cloud.githubusercontent.com/assets/20861826/17444835/8995b82a-5b5b-11e6-85e0-f7c1613fa390.png)

**Comment by khurramkhanmr** [comment]
can we do with timeline code. or do I need to create class for this.

**Comment by khurramkhanmr** [comment]
Can you please any sample .FLA having plugin embedded and at least initialized. please thanks

**Comment by khurramkhanmr** [comment]
I followed the directory structure mentioned in video but still no success

**Comment by khurramkhanmr** [comment]
also did XML permission in manifest file.

**Comment by khurramkhanmr** [comment]
Can we do a skype session please.

skype: khurramkhan2009

**Comment by khurramkhanmr** [comment]
I have recreated the project . and it seems the .ane into the project now. 

I 	trace("Billing "+Billing.EXTENSION_ID + "  "+Billing.ANDROID +"    "+Billing.VERSION)

output: Billing com.myflashlab.air.extensions.billing  android    2.0.0

is it mean .ane is there and working? .  when I compile its stuck on it and after a few minutes shows msgs:

when i click on test ANE button:
 it shows errors
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at Function/<anonymous>()
	at Function/http://adobe.com/AS3/2006/builtin::apply()
	at SetIntervalTimer/onTimer()
	at flash.utils::Timer/_timerDispatch()
	at flash.utils::Timer/tick()
Cannot display source code at this location.

**Comment by myflashlab** [comment]
Nope, those are constant values and does not means that the ANE is embedded. Please email us your demo project to have a look at your setup. (Make sure your fla file can be opened with FlashCC) http://www.myflashlabs.com/contact

**Comment by khurramkhanmr** [comment]
thanks for your support, I will email FlashCC files to you

I think its not working on adobe air simulator . I am trying to publish and install on device via usb . 

it seems working but on init response status got = 0

**Comment by khurramkhanmr** [comment]
finally got msg. no product match found on server! on the device

**Comment by khurramkhanmr** [comment]
[testing in app payments.zip](https://github.com/myflashlab/inAppPayments-ANE/files/404767/testing.in.app.payments.zip)
[inAppPayments.zip](https://github.com/myflashlab/inAppPayments-ANE/files/404768/inAppPayments.zip)

source code and licensed .ane are attached.

**Comment by myflashlab** [comment]
Email us immediately.
