### ISSUE TITLE
Demo Project

### ISSUE THREAD

**Issue by khurramkhanmr** [myflashlab/inAppPayments-ANE#19]
As demo  video i have created demo project.

FLASH CC: when i click on test ANE button:
it shows errors using simulator 
```
ArgumentError: Error #3500: The extension context does not have a method with the name command.
at flash.external::ExtensionContext/_call()
at flash.external::ExtensionContext/call()
at Function/()
at Function/http://adobe.com/AS3/2006/builtin::apply()
at SetIntervalTimer/onTimer()
at flash.utils::Timer/_timerDispatch()
at flash.utils::Timer/tick()
```

but when i connect Android device with usb cable and publish on device . it seems working but getting msg:

status = 0, and $msg = no product match found on server!

**Comment by myflashlab** [comment]
The extension cannot run on a simulator. You will need a real device to test and debug your app. for the other error you are receiving, please check here: https://github.com/myflashlab/inAppPayments-ANE/blob/master/FD/src/MainFinal.as#L220-L238

**Comment by khurramkhanmr** [comment]
Thanks for your help, the  air.com.testid , it was wrong. i used the same package id its working fine and return me the available product on store.  now let me try to purchase  this product. 
do i need to create test account ?

**Comment by khurramkhanmr** [comment]
facing problem when using dopayment. please check the attached image. i entered the same productId.

Billing.doPayment(BillingType.CONSUMABLE, "android.test.myPid", "Payload CONSUMABLE", onPurchaseResult);
![screenshot_2016-08-07-05-30-33](https://cloud.githubusercontent.com/assets/20861826/17459776/9e9b3118-5c60-11e6-9276-fb3ef87c33ba.png)

please advise - thank you

**Comment by khurramkhanmr** [comment]
Thanks for your response.

I have gone through with the given suggestion but still didn't find any solution to purchase item. i can see the products id's but not when try to purchase and called (do payment method) it says "no product available on the stores", please see the attached image on the forum.



________________________________

**Comment by myflashlab** [comment]
One common mistake is that you need to make sure that you have set a test account in your google play consol. Are you trying to make a test payment using your test account?

**Comment by khurramkhanmr** [comment]
Yes I have created the test account, but still no success , do i need to upload the .apk on the store first and than test ? its currently in live mode. not in alpha or beta.

________________________________

**Comment by myflashlab** [comment]
Well, the tester accounts would work with alpha or beta channels. If your app is live and published, you should be able to make real payment tests with real accounts.

I must add that all of the settings related to this ANE works exactly like the Android side. You might try searching Android forums for similar problems and their suggestions might help you pass the barrier. 

If that does not help, maybe you should contact us through www.myflashlabs.com and we can schedule a Skype meeting?

**Comment by khurramkhanmr** [comment]
Team, thank you for your response and support.  ANE seems working and its showing me one product id from 2 , i created on the google play-store , in the C.log console of the demo project.  I think that would be good if we can do a skype meeting and pass this barrier.  I hope the session will be really helpful for us.

**Comment by khurramkhanmr** [comment]
Please Help

**Comment by khurramkhanmr** [comment]
Found solution: I uploaded the .apk on the store and than download it, seems working :), now i can see the inapp popup

**Comment by myflashlab** [comment]
It really should have worked without needing to do that! but we're happy that you finally solved the problem. We had no more solutions :) You know, the security parameters on in-app payments are very high on both Google and Apple and that's why it's hard to get things to work at the first time. but once everything is setup, then the rest is a breeze.
