### ISSUE TITLE
SKU Details

### ISSUE THREAD

**Issue by MaksBrainiac** [myflashlab/inAppPayments-ANE#2]
How can I get product details (price, getSkuDetails)?

**Comment by myflashlab** [comment]
fetching the product details is currently considered as a private Array method access through ```_ex._launcher.confirmed_products``` *But, you are not encouraged to use it right now.*

We have marked this feature to make it public in the next coming release. until then you should inject the price and other product information yourself into the app. You are already injecting the product IDs like below. you should also hard-code the product details for now.

```actionscript
Billing.init("ANDROID_KEY", 
[	// Android product IDs which you have already set in your Google Play console.
	"test01", 
	"test02", 
	"test03", 
	"test04"
], 
[	// iOS product IDs which you have already set in your iTunes Connect.
	"inappbilling_auto_renewable_one", 
	"inappbilling_consumable_one", 
	"inappbilling_managed_one", 
	"inappbilling_managed_two"
], onInitResult);
```

As soon as we release the new version, you'll have access to them.

**Comment by qdrj** [comment]
Hi,

I really-really need product price and can't hardcode it because I need price in local currencies. 

Is there any way to access _launcher property?

I can see it in the debugger along with confirmed_products array. But I can't access it via code. I get error: 

> [Fault] exception, information=ReferenceError: Error #1069: Property _launcher not found on com.myflashlab.air.extensions.billing.Billing and there is no default value.

**Comment by myflashlab** [comment]
Please update to V2.0.0 and this feature is now public. [read the changlog here.](https://github.com/myflashlab/inAppPayments-ANE#changelog)
