### ISSUE TITLE
App started crashing on iOS during Billing.init().

### ISSUE THREAD

**Issue by Adrian-S** [myflashlab/inAppPayments-ANE#22]
OK, so we had the app ready to be shipped out, everything was testing perfectly, but app got rejected once because we wanted to sell items starting from a specific date and shop was not open when they tried to test. We fixed that and now it got rejected for the second time, and they say it's because IPv6 and it's crashing. So same app submitted for review did not crash the first time and started crashing the second time.

But the most impressive achievement so far, is that I can't build the app any more and it crashes in iOS sandbox too. If I try to run Billing.init a crash will happen about 2-3 seconds later, and my callback function for init, is not even called.

I have no idea if Apple did anything to the items sold. But my ultra fast solution was to change the code back to productStore ANE from Adobe, and trough some random luck I found the 64bit versions. We had this before but decided to get your ANE for Android, and used it for iOS too. And yes, productStore ANE still works to my great surprise.

Never the less I will want to be able to use your ANE in the future and I have no idea how to start debugging. Remote debugging simply closes with no error.

Thanks.

**Comment by myflashlab** [comment]
Will you be able to connect your device to your mac and send us the error log generated in xcode debug console? are you sure you have setup everything correctly? It is weird that the ANE worked at some point and then suddenly stopped! maybe something has changed in your setup?

**Comment by Adrian-S** [comment]
This is a crash log file they sent. We don't have a mac, we use a virtual machine to upload the files. I've also noticed the in-app products were marked as "Developer Action Needed" and I think they didn't like the name of the products. If there is a procedure to get the product names, that productStore ANE from Adobe doesn't have, it might explain some stuff. I've only updated the names of the in-app products a few hours ago.

I did send them a message asking if there is anything we need to do, and they told me no action was needed. I think they didn't look at the products. Got to love the automated replies. And if it crashed on IPv4 when I tested, it means they did a poor job of testing the app and sent me on the wrong path chasing IPv6 errors.

[temp..eclroldg.crash.txt](https://github.com/myflashlab/inAppPayments-ANE/files/476575/temp.eclroldg.crash.txt)

**Comment by Adrian-S** [comment]
Great news, they reviewed the same IPA again and the products were approved too and most of it is working fine. I downloaded the app on another device and I don't get the products on the live app. For now I will just assume I'm in the wrong iTunes Store and not worry about it until tomorrow.

**Comment by myflashlab** [comment]
Good to know the problem is fixed. Apple really gives a hard time to developers. We have numerous samples that something didn't work at first and then the same thing worked later. and also the opposite! Something worked perfectly tonight and the very same thing crashed tomorrow morning. These usually don't happen on Android. As far as we have learned, when it comes to iOS, we need to be calm and try again later :laughing:
