### ISSUE TITLE
Debug Mode in iOS returns "No product match found on server!"

### ISSUE THREAD

**Issue by DenisSokoloff** [myflashlab/inAppPayments-ANE#25]
Debug Mode in iOS returns "No product match found on server!"
I used last v32 ANE

**Air SDK:**
v.24 (28 October)

**My in-app purchases**
http://prntscr.com/d189gc

**Set:**
`<key>MinimumOSVersion</key>
<string>7.1</string>
`
` <extensions>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
  </extensions>
`

**Ane included**
http://prntscr.com/d18axo

**Debug Set**
`Billing.IS_DEBUG_MODE = true;`

**Code On iPhone 6 (10.1)**
http://prntscr.com/d18c1j

**Return** 
Billing.products = null
status = 0
msg = "No product match found on server!"

**Comment by Wpdas** [comment]
The same error for me. I don't receive any item.

**Comment by Wpdas** [comment]
After of set up Bank informations and Tax... load all items! See this link: https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/ManagingContractsandBanking.html

**Comment by myflashlab** [comment]
Setting the bank details and and taking care of Apple agreements is surely required before your in-app-purchase items can work as @Wpdas suggested.

Moreover, there might be other reasons you should check, explained [here](https://github.com/myflashlab/inAppPayments-ANE/blob/master/FD/src/MainFinal.as#L234-L238)

Let us know how it goes.
