### ISSUE TITLE
Application crashes on IOS

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/inAppPayments-ANE#26]
Hello, 

Our application crashes on IOS after initialization of inAppPayments ANE. This happens always. We saw the same behavior on two devices with IOS 9. Earlier the ANE was working, but maybe the crashes started after IOS update.  If you disable network, the game doesn't crash.

I think it would be easily reproducible. Please, check it asap and let us know. We were forced to stop our app because of this issue.

We will continue to experiment and provide any interesting info we will find. Our code is very simple. We use the AS3 code from your gitHub repo almost without changes.

Tested on:
iPod Touch 5, IOS 9.3.5 - crash
iPhone 4, IOS 9.3.5 - crash

AIR 23 build 257
inAppPayments ANE from packageV32

Note that iPhone 4 and iPod Touch 5 devices are stuck with iOS 9, so this issue might make impact on too many users.

**Comment by myflashlab** [comment]
It's very unlikely that an iOS upgrade would cause such an important tool like in-app-purchase to fail. Apple might do a lot of crazy stuff but they would never do something that would cause them make less money 😆 

Anyhow, We tested the ANE again on iOS 9.x.x and 10.x.x different versions and it is surely working fine. There must be something else in your app causing this.

Moreover, iOS upgrade to 10 should not have any impact on earlier versions. So if your iOS 9.x.x devices are also crashing, it again means that something else is going wrong in your build.

The only advice we can give at the moment, is for you to try the new AIR 24 and see how it might go?

**Comment by UmberFunk** [comment]
So, after making lots of experiments, I found the reason...

When we submitted our game for review, review team rejected the build. They decided that the in-apps we made as consumables needs to be non-consumables. They marked the in-app products as "Developer Action Needed" and looks like this made some change to its functionality. Our app was crashing when this in-app products were initiated at startup.

I don't know why it's needed to change functionality to the in-apps when they are marked as "Developer Action Needed". Maybe we still need them for testing........

We use Facebook for game account registration, so all the purchases are able to be restored using Facebook Connect and we don't need non-consumable in-apps linked to Apple ID. 

Now I need to tell Apple to unmark the in-app products and reactivate them to continue testing and submit new release.............

**Comment by myflashlab** [comment]
grrr, Apple review trouble again. Sorry to hear that. I hope they can unmark your in-app items. So, as far as this ticket, I think it's now safe to close it, right?

**Comment by UmberFunk** [comment]
Sure, you are free to close the issue.

Sorry for taking your time. I wasn't able to think that Apple might be responsible for this issue....

Maybe it would be good to add some security thing to avoid crashing of application in similar scenarios and log that there's problem with disabled in-app products, but I don't know if it's worth your time. 

Regards and thanks!
