### ISSUE TITLE
no response of Billing.init("myKey",["purchase"],["purchase"], onInitResult);

### ISSUE THREAD

**Issue by FuchsEmmanuel** [myflashlab/inAppPayments-ANE#28]
I have no response of Billing.init. 
The function onInitResult is not called after initialisation. I don't know what happened because I have no feedback from the ANE in the onInitResult fonction...

 Thanks for your feedback.

Emmanuem

**Comment by myflashlab** [comment]
Is this happening on iOS or Android? Either case, please try to connect your ios device to AndroidStudio or xcode and send us any possible logs when you init the ANE.

Moreover, try to check the closed issues which you may find some hints. As in app billing is very sensitive to how you have setup your app developer account...

**Comment by FuchsEmmanuel** [comment]
It happens on Android. 
Is it possible to see what happened with flash builder? 

Could you give me some example fo 'very sensitive to how you have setup your app developer account"

For your information, 1  week ago, everything worked well. I have updated my apk and added some language and the inapp purchase doesn't work any more. 

If there is not response from onInitResult method, does it means it comes from the google play developper setting?  What's happening if you write a wrong key or product? Do you have a feedback?

Thanks in advance

Emmanuel

**Comment by FuchsEmmanuel** [comment]
Hi,

I have found my error but an new issue is still present.

First, I have forgot to add  androidSupport.ane  & overrideAir.ane in my apk.

But now, with these 2 ane, there is a conflict with another ane GoViral from  milkmangames :(... (see below the error message from Flash Builder)
Before your update of inAppPayments.ane (9 Nov), there was no conflict between these 2 ane (inAppPayments_previous release and GoViral)


I don't want to rewrite all my source code of social network part .So I would like to have the previous release of inAppPayments.ane. I worked well with this release because we don't need  androidSupport.ane  & overrideAir.ane.

Could you send me this previous release of inAppPayments.ane without DEMO (Billing.DEMO_ANE = false). I can upload from your server this version.


Thanks in advance for your help..


Now I know the difficulties to manage different Ane. I will update my app step by step for using only flashLab Club ane... :)


Thanks in advance again.

All the best.

Emmanuel

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/v4/view/MenuItemCompatHoneycomb;
                at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
                at com.android.dx.dex.file.DexFile.add(DexFile.java:161)

**Comment by FuchsEmmanuel** [comment]
It is very important for me to keep my goviral.ane in my code because **Firebase Invites (Coming soon)** is not supported right now.

**Comment by myflashlab** [comment]
try removing the ``` androidSupport.ane``` while keeping the ```overrideAir.ane``` and see how it goes.

**Comment by FuchsEmmanuel** [comment]
OK Je teste...

2016-12-10 9:29 GMT+01:00 MyFlashLabs <notifications@github.com>:

**Comment by FuchsEmmanuel** [comment]
Hi,

It's work. I did not make a purchase until the end but Billing.init works
well.
Thanks for this quick and smart support.
Have a nice week end

Emmanuel

PS: I added your workaround on github: you can close the issue.



2016-12-10 9:31 GMT+01:00 Emmanuel Fuchs <emmanuel.fuchs@biziip.com>:

**Comment by FuchsEmmanuel** [comment]
Remove androidSupport.ane and keep overrideAir.ane => It works

**Comment by myflashlab** [comment]
Glad it worked. Make sure you are preparing to use ANEs from the club only in near future because such tricks might not work on all ANEs :)

**Comment by FuchsEmmanuel** [comment]
Yes of course... I will migrate as soon as possible.. !

2016-12-10 9:52 GMT+01:00 MyFlashLabs <notifications@github.com>:
