### ISSUE TITLE
How to reset Purchases during testing?

### ISSUE THREAD

**Issue by leossmith** [myflashlab/inAppPayments-ANE#29]
Hi, i am trying to add IAP in one of my apps. During Android testing, i "purchased" the item, but now i can't continue testing as it has been already in my inventory. Is there a way to delete it? Is there an other way to test on android? 

I have Billing.IS_DEBUG_MODE=true;

**Comment by myflashlab** [comment]
This is explained in these lines: https://github.com/myflashlab/inAppPayments-ANE/blob/master/FD/src/MainFinal.as#L192-L210

> When developing, you may need to consume an already owned item. On the Android side, you may do as follow:
			 *	
			 *	Billing.forceConsume("productId", onResult);
			 *	function onResult($result:Boolean):void
			 *	{
			 *		if($result)
			 *		{
			 *			// your purchase has been consumed successfully
			 *		}
			 *		else
			 *		{
			 *			// something went wrong! You may try again.
			 *		}
			 *	}
			 * 
			 *	Unfortunaitly on the iOS side, you get "one shot" to buy your item because Apple remembers that your account has purchased that item. 
			 *	If you need to test again, you need a different test account. There is no way to reset these purchases like how we can in Android.

**Comment by leossmith** [comment]
Oh, OK so basically we never reset the purchase. I have to force it during debugging. Thanks for your quick reply. I will try that as soon as google returns the products from the server.

**Comment by myflashlab** [comment]
All good here?
