### ISSUE TITLE
IOS Receipt Validation

### ISSUE THREAD

**Issue by MaksBrainiac** [myflashlab/inAppPayments-ANE#3]
How can I get IOS Purchase transactionReceipt?
It's needed for on server purchase validation.

**Comment by myflashlab** [comment]
You should expect this feature on the next release of the ANE. on the first release of our ANE we fully concentrated on making the ANE work 100% the same on both Android and iOS platforms. but there are a few differences like the one you mentioned that we will make them public on the next release. Please make sure to signup in the newsletter to know when this is released http://www.myflashlabs.com/contact/

**Comment by fu-iq12** [comment]
It wasn't part of the 2.0 release. Is it still on the roadmap?

**Comment by Riftwar** [comment]
Has this feature been added yet? If it hasn't will it be implemented in the near future.

**Comment by arsyad** [comment]
Is this feature available? I am seeing some purchases made but it doesn't get recorded in iTunes. Suspect that it could be a fake purchase. How can we verify the transaction is legit? Is there a need to do server side validation other than from the purchase result?

**Comment by gameaccount** [comment]
Hi @myflashlab,

It seems this is still not available in the latest release (v 2.1.0).
Can we expect an update with this feature in the near future?

Thanks

**Comment by myflashlab** [comment]
Yes of course. we are busily working on a BIG update on how ANEs are developed in general, as soon as that is finished we will start updating the ANE features and this request is near the top of our to-do list... We're on it :)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
