### ISSUE TITLE
Some users can't purchase on Android

### ISSUE THREAD

**Issue by Samuramu** [myflashlab/inAppPayments-ANE#30]
I am using the ANE successfully for a while, however several weeks ago started getting emails from users who can't purchase the in-apps on Android.

There still are some purchases, that's how I know it is probably configured alright.

I'm using v1.2 - Is this something to do with recent changes on Google Play API?

**Comment by myflashlab** [comment]
The current ANE version is V2.1.0. We are constantly trying to keep the ANEs updated with the latest SDK changes. Try updating your app with the latest ANE and see how it goes.

**Comment by Samuramu** [comment]
Thanks, problem is I have a conflicting ane (pusheoosh) when I do that,
since the update introduces common libraries.

**Comment by myflashlab** [comment]
Try not implementing the ```androidSupport.ane``` dependency and see if it compiles fine? it probably should work fine when other ANE has it already. 

**Note:** you should consider replacing the conflicting ANEs with other alternatives. Have you considered switching to Firebase FCM instead of pushwoosh? just a suggestion :)

**Comment by Samuramu** [comment]
It DID actually compile fine when i did that, I'm just worried it will
break something under the surface. Now testing in beta.

**Comment by myflashlab** [comment]
If it works and you can make a purchase, then you'll be fine but as said earlier, you should consider upgrading to the latest versions with all the dependencies. I'm now closing this issue but feel free to open a new one if required.
