### ISSUE TITLE
Crash at app startup when IAPs are initialized. Problem with AppStore submit process.

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/inAppPayments-ANE#32]
Hello,

Our app was rejected several times because of this ANE.

I have sent you an email about this BUG on Jan 21 and reminder 11 days ago, but still there is no answer.
Also, I have notified you about this issue Nov 8, 2016: https://github.com/myflashlab/inAppPayments-ANE/issues/26

Now I'm trying to reach you here.

When we submitted our app on AppStore for the first time, our app was rejected just to clarify some details about restore mechanism. After this reject, exclamation marks arrived next to our IAPs on iTunesConnect portal. After this exclamation marks arrived, In-App Purchase ANE started to crash our app when this IAPs were initialized at app startup. Apple guys were unable to continue testing, as app was crashing at startup.

Our working process is badly impacted by this bug and delay in fix.

Several months ago we had another problem and you also didn't responded for a long period.

We started to think it would be safer to move to another ane developer like Milkman or Distriqt, despite the work needed for this changes.

Hope you will fix it very soon.

**Comment by myflashlab** [comment]
@UmberFunk We really like to be able to help you on this regard but there is not enough information on how we might debug the problem. The thing is that we are not receiving a similar issue/ticket like what you are experiencing which gives us a feeling that this should be probably causing by something else in your application.

Have you happened to run your application with the adhoc build? does that work ok?

**Comment by UmberFunk** [comment]
I have sent you crash log files 26 days ago on your support email.

Everything worked correctly until exclamation marks arrived in iTunes Connect. Our app crashes when initialization of marked IAPs happens at app startup. We removed the IAPs and tried with new test IAP and it worked. It can't be a mistake in our code. 

I can provide you with all available info I have if you make it very quick. You can call me on Skype - Irakli Geleishvili

On 16 or 17 Feb we will switch to other provider of ANEs.

**Comment by UmberFunk** [comment]
P.S. Sure, we have run adhoc version. Then we have run TestFlight version and then submitted to review.

After exclamation marks, app crashes in adhoc, testflight and appstore versions,

**Comment by myflashlab** [comment]
The iOS crashlogs are almost useless for AIR applications and we can't read much information from them. [this is an old post but you *might* find it helpful](http://blogs.adobe.com/rajorshi/2011/11/18/debugging-native-extensions-for-air-ios/)

> On 16 or 17 Feb we plan to switch to other provider of ANEs if we'll be unable to make this ane work.

You have every right to do that, but I strongly think that something else is causing the problem in your app.

Anyway, let's try this: If you have a beta testing  environment ready for your app, send us an invitation so we can test the app and see the crash locally. If you don't have the beta testing setup, I have emailed you our iOS device UDID so you can add it to your provision and send us the .ipa file so we can run the app and see the crash locally. Maybe we can spot the problem?

**Comment by UmberFunk** [comment]
I have sent you an email with IPA.

**Comment by myflashlab** [comment]
Please close this ticket if you don't have more questions.

**Comment by UmberFunk** [comment]
Is the ANE still crashing after iOS reject?

**Comment by myflashlab** [comment]
@UmberFunk I believe we have discussed this issue on email which was related to the title of the products missing on the iTunes...?!

**Comment by UmberFunk** [comment]
Yes, looks like iTunes doesn't return value if app is crashing. You already know it, but did you do anything to avoid crash of your ANE?

I have found a workaround after you said that ANE doesn't receive value, but if ANE still crashes, that means issue still persists.

**Comment by myflashlab** [comment]
The upcoming V2.2.0 will have a static string replaced with the title and description if they are null from iTunes. However, we do not consider this a bug. It's a silly thing from iTunes. Anyway, Thanks for finding and reporting this.
