### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name command.

### ISSUE THREAD

**Issue by pdavik** [myflashlab/inAppPayments-ANE#33]
I'm getting this error. 👍 
ArgumentError: Error #3500: The extension context does not have a method with the name command.

Ive already added  androidSupport.ane and overrideAir.ane. It still not running, what am i missing?

**Comment by myflashlab** [comment]
This error message means that the ANE is not embedded in your project. The first question is if you are running on a simulator? if so, try to run it on a real device. And if you are running on a real device and still see this error message, you might want to watch these videos to see what are you probably missing: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by myflashlab** [comment]
Please let us know if the problem is solved?
