### ISSUE TITLE
ANE runs DEMO VERSION popup: Rejected from App Store

### ISSUE THREAD

**Issue by finleywilliamsonV** [myflashlab/inAppPayments-ANE#35]
What could cause the DEMO VERSION popup to still be displaying?

I am not setting Billing.IS_DEBUG_MODE = true.

To my knowledge I am using the Full Version ANE that I purchased.

**Comment by myflashlab** [comment]
If you are seeing the "DEMO" dialog, that means that you are using the demo ANE downloaded from our GitHub repository. If you have purchased a license, you need to replace the ANE with the one in the package you purchased. That will make the dialog go away

FYI: ```Billing.IS_DEBUG_MODE = true``` has nothing to do with the DEMO dialog.
