### ISSUE TITLE
Google Play Signature

### ISSUE THREAD

**Issue by MyMyGames** [myflashlab/inAppPayments-ANE#37]
To check the purchase on the server, i need {{Google Play signature}}.
Where can i get the "signature"?
It is "data.purchaseToken"?

**Comment by MyMyGames** [comment]
Anybody home?

**Comment by myflashlab** [comment]
could you post us a link to this? do you mean the signature edition thing?!

**Comment by MyMyGames** [comment]
https://api.playfab.com/documentation/client/method/ValidateGooglePlayPurchase

https://developer.android.com/google/play/billing/billing_reference.html#getBuyIntent

Response data from an In-app Billing Version 3 purchase request.
Key	Description
RESPONSE_CODE	Value is 0 if the purchase was success, error otherwise.
INAPP_PURCHASE_DATA	A String in JSON format that contains details about the purchase order. See table 6 for a description of the JSON fields.
INAPP_DATA_SIGNATURE	String containing the signature of the purchase data that was signed with the private key of the developer. The data signature uses the RSASSA-PKCS1-v1_5 scheme.

INAPP_DATA_SIGNATURE

**Comment by myflashlab** [comment]
Purchase signatures will be returned on the upcoming new version (2.3.0) of the ANE.
