### ISSUE TITLE
TypeError #1009: Null Object Reference when calling Billing.init()

### ISSUE THREAD

**Issue by obuw** [myflashlab/inAppPayments-ANE#38]
I'm having trouble getting the ANE to work. Whenever I try to call Billing.init(), I get this runtime error:

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.billing::Launcher()
	at com.myflashlab.air.extensions.billing.android::Android()
	at com.myflashlab.air.extensions.billing::Billing()
	at com.myflashlab.air.extensions.billing::Billing$/init()
	at MainFinal/init()[MainFinal.as:170]
	at MainFinal()[MainFinal.as:97]
```

I'm using flashdevelop, trying to call it from my existing app as well as from the example. Both running from the desktop, and from my android device (Samsung S5) I get the same error.

Is this because the google / apple accounts are not set up properly? I have copied the Android in-app-billing key, and I have entered the product id, like so:

`Billing.init("androidkey", 	["test_purchase"], [], onInitResult);`

We don't have an apple account yet so I have left that section as an empty array.

Is there anything I can do to troubleshoot why things are not working?

**Comment by myflashlab** [comment]
This error means that the ANE is not correctly embedded in your project OR you are trying to run your app on a simulator. watch these videos: you might find them helpful https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by obuw** [comment]
Okay, I have managed to get it working. But I believe it would be helpful if there was an actual error message when running from a simulator, instead of a runtime error. Or at least if the example had a try/catch clause that covered that possibility. Other ANEs I use usually do this. Just a suggestion.

Thanks for the help!

**Comment by myflashlab** [comment]
Actually we do have a tool to do that. You may read this post: http://www.myflashlabs.com/a-tool-to-make-ane-integration-into-your-air-apps-a-breeze/
