### ISSUE TITLE
Successful test purchase crashing App on Android

### ISSUE THREAD

**Issue by lerpinglemur** [myflashlab/inAppPayments-ANE#39]
I don't have too much information on this yet.. Cancellation succeeds but a successful test purchase crashes the app. I have a separate purchase-ANE for iOS that works fine.
Since the code runs through an interface, there aren't many places where my own code could be causing the issue, but I'm ruling out possibilities. Does anyone else have this issue?

**Comment by lerpinglemur** [comment]
For more details, all my product ids are correct and active. Init() callback succeeds for the products.

I was getting the correct purchase dialogs which asked me to make a purchase. i have tried with the Billing.DEBUG both true and false.

Now when I even START to make a purchase that crashed when it succeeded the time before, it will crash just by requesting it even once.

**Comment by lerpinglemur** [comment]
When I attempt to restore purchases, the length of the returned array is 1947. I have done a lot of testing.. but there is no way I've test-purchased that many items -- and they'd be duplicates or nulls in any case. The app then crashes before the output hits my debug display to see what the ids are.

**Comment by myflashlab** [comment]
Please check [this issue](https://github.com/myflashlab/inAppPayments-ANE/issues/21) and see if it's related?

**Comment by lerpinglemur** [comment]
This cannot be related. I do not have 20 products. My init() function succeeds. Purchase does not.



________________________________

**Comment by myflashlab** [comment]
Please try V2.2.1 of the ANE being just released. This might be the same problem as described here #40 ?

**Comment by lerpinglemur** [comment]
I don't care. That was over a month ago. I already released the app using Milkman's plugin.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
