### ISSUE TITLE
Massive list of "null" purchased products (onGetPurchasesResult)

### ISSUE THREAD

**Issue by rdoi** [myflashlab/inAppPayments-ANE#40]
Setup:
Compile platfom: Adobe Air 25.0 Win10 x64
Testing device: Galaxy Tab3 7.0 (lt02wifi) [SMT210]
Android Kitkat 4.4.2
Google Play Store: 7.6.08.N-all [0] [PR] 149245622

I have filled a issue (https://github.com/myflashlab/inAppPayments-ANE/issues/36) a while ago, but didn't realize it was actually a two part error. 
So, the first part (the Base64DecoderException error) was a mispelled GoogleID key. This was easily solved by re-copy&paste the key.

But, the real error (2nd part) was an app-crash that followed it. This is caused by an "infinite" loop of "null" products on onGetPurchasesResult. This is probably the same problem already reported in:
https://github.com/myflashlab/inAppPayments-ANE/issues/15?_pjax=%23js-repo-pjax-container#issuecomment-231907607 and https://github.com/myflashlab/inAppPayments-ANE/issues/34

To organize the issue, this is our background:
* All our tests are in Air/Android environment. (iOS tests would follow after validating android workflow)
* We compiled the default ANEs demo app in our test device. It listed and purchased the googles "dummy" product (android.test.purchased) and everything was fine.
* We setup our store in Google play and added 3 products.
* We created a dummy gmail user, added him as a beta tester and in the store "financial exception" list (to avoid effective billing). This dummy user was setup as our test device's google play account.
* In the app, we replaced the GoogleID and added our products ids.
* #36 ERROR happened. So fixed the GoogleID.

At this point, the init was successful. It was connecting to our google store, and retrieving correctly our 3 products with their respective prices.

Then we tried our first purchase:
* We then triggered Billing.doPayment with BillingType.PERMANENT and one of our consumable product id, correctly listed previously.
* It correctly fired the GooglePlay store purchase modal, it said that it will not be charged (he is in our store exception list). But it asked for a valid credit card anyway, and then it seemed to finish the purchase successfuly.
* However, in the trace log we noticed that its returning purchase data had an invalid (0 or null) orderId and purchaseToken. Well, we believed it may be because we are using a test user that doesn't dispatch a real billing in the store.

The problem:
* After the purchase, we tried to retrieve the purchased item (onGetPurchasesResult), expecting to see this product listed. 
* The app then freezed for a while and crashed ("stopped responding") to device's home screen.
* In the google store app, we can see the bought product was correctly listed as purchased (with zero price tag).
* We tried to run the app again. It listed our store products correctly, but crashed again when tried to list the purchased items.
* After some breakpoint investigation, we noticed that the returning array of purchased items have a massive number of items. All with invalid product data (null, empty, zero):
```
----------------
purchaseData.orderId = null
purchaseData.productId = null
purchaseData.purchaseState = 0
purchaseData.purchaseTime = 0
purchaseData.purchaseToken = null
----------------
```

Actually, the for-loop in this array was causing the crash. If we limit the loop to a sane number (like 50) it will print this invalid product 50 times, and then returns normally, but never bringing up our purchased product, not once.

Some times (not always) it catches an error while debugging:
```
Using Apache Flex SDK 4.13 Debugger Adapter (Worker support).
[Info] Ask port 7937.
[Info] Connection as client to player via 7937 established.
[Loading] Loaded: ex.swf
Exception fault: undefined
	at flash.data::SQLStatement/execute()
	at Function/<anonymous>()
	at Function/<anonymous>()
	at flash.data::SQLStatement/internalExecute()
	at flash.data::SQLStatement/execute()
	at Function/<anonymous>()
	at Function/<anonymous>()
	at Function/<anonymous>()
	at flash.data::SQLStatement/internalExecute()
	at flash.data::SQLStatement/execute()
	at Function/<anonymous>()
	at Function/<anonymous>()
	at Function/<anonymous>()
	at flash.data::SQLStatement/internalExecute()
	at flash.data::SQLStatement/execute()
	at Function/<anonymous>()
	at Function/<anonymous>()
	at Function/<anonymous>()
(... repeats a lot of times)
```
Of course we tried to call Billing.clearCache(), reinstall the app, and to clear the app and the google play app cache. And now, no matter what, it will always bring this massive list of nulls when trying to retrieve the purchase list.

We then tried the same with a brand new dummy user, with the same settings, and it all happened again.

We do suspect that maybe this happens because these users are in our store's billing exception list, and then it returns an invalid (orderid==null) purchase response. 

Well, we didn't try a real purchase, with a real user account and a real billing in the credit card yet. But not inclined to do it so soon.

Anyway, any clue?

**Comment by myflashlab** [comment]
Here are some questions:

1. Is your app in English language only?
2. Have you added your test users to Settings > Developer Account > Account Details > License Testing ?
3. When not using the dummy product IDs, you must have set the ```Billing.IS_DEBUG_MODE = true;``` to false, have you done that?
4. Is your apk in beta or alpha upload?

Will you be able to send us AndroidStudio/logcat error stack? That would be great because with the logcat we can see where the error is initiated and we can build a demo debug ANE for you to identify the problem. Please let us know.

**Comment by rdoi** [comment]
> 1. Is your app in English language only?
In the current setup, yes. But it will be multilang on release.

> 2. Have you added your test users to Settings > Developer Account > Account Details > License Testing ?
Yes.  

> 3. When not using the dummy product IDs, you must have set the Billing.IS_DEBUG_MODE = true; to false, have you done that?
Not at all. By reading the related comment on demo code, we assumed the DEBUG_MODE= false was only necessary when compiling the release version. We may try it set as false later to see if it will make any difference.

> 4. Is your apk in beta or alpha upload?
Tried on alpha and beta. Not on release.

> 5. where is store's billing exception list?!
The "License Testing" option as mentioned on item 2.

> Will you be able to send us AndroidStudio/logcat error 
ATM, I don't have the android studio nor its logcat installed. Is there any other way to dump these errors?

**Comment by myflashlab** [comment]
That would help a lot if we can see where the error is initiated. Download AndroidStudio, create a dummy Android project then open the logcat window while you are running your app. then you will see the logs. Please try that. But before that, do # 3 first. That may be the reason.

**Comment by carlosranoya** [comment]
We did # 3 and resualt was the same.

The AndroidStudio/logcat error stack was empty.
I don´t know if it´s useful, but below I linked the full log:

[catlog_android studio.txt](https://github.com/myflashlab/inAppPayments-ANE/files/1042114/catlog_android.studio.txt)

**Comment by myflashlab** [comment]
Ok, Please hold on till we build a debugged version of the ANE for you... we'll send it over here with the description about how to get the debug information. We are VERY interested to find the reason why some devs are facing this similar problem. Hold on while we build a new debug ANE... Thanks.

**Comment by rstaliba** [comment]
Ok, we are waiting for the debugged version of the ANE and the description about how to get the debug information. Thank's.

**Comment by myflashlab** [comment]
Alright, Please replace your ANE with this one: https://drive.google.com/open?id=0B7eHG2CEml2Tbzdjd2F5RnJwaWc

Now, before you run your project, enable debugging using the [override ANE](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir)

```actionscript
// add this import so you will have access to the OverrideAir ANE llibrary
import com.myflashlab.air.extensions.dependency.OverrideAir;

// add this before you init the billing ANE
OverrideAir.enableDebugger(myDebuggerDelegate);

private function myDebuggerDelegate($ane:String, $class:String, $msg:String):void
{
	trace("["+$ane+"-"+$class+"]"+$msg);
}
```

Now do what you do to make the error happen and send us all the trace outputs. It would be even better if you are sending the logs in packs, meaning, separate them when you are calling any billing ANE methods.

**Comment by akuklev** [comment]
We have exactly the same issue. It blocks shipment of our beta. Can we hope it will be resolved soon?

**Comment by felipecgonc** [comment]
Hi, I'm stumbling upon the same issue in an app that needs to be published by Wednesday. In my case, I can set up a very lousy but temporary solution (storing whether items were purchased locally on the app's data) as the app will be a new release. But it would be great to have the fix ASAP, since it will most certainly cause problems in the long run.

**Comment by myflashlab** [comment]
Guys, please read this post again: https://github.com/myflashlab/inAppPayments-ANE/issues/40#issuecomment-305959643 and use the linked debugging ANE instead of your current one, then use the suggested ```myDebuggerDelegate``` to trace out the logs. Send us that logs and we can investigate this more. Please work with us so we can identify the bug and kill it once for all.

**Comment by jankri** [comment]
I managed to produce the logs using the debugging ANE. How should I send them to you? I would not like to post it here because of real product ids inside.

**Comment by myflashlab** [comment]
@jankri good, please send the logs to http://www.myflashlabs.com/contact/ while linking to this issue so they know they should send the content to the dev side directly. Thanks.

**Comment by jankri** [comment]
@myflashlab done

**Comment by felipecgonc** [comment]
@myflashlab Done!

**Comment by myflashlab** [comment]
Thanks guys, we are looking into the problem. will update you a.s.a.p

**Comment by felipecgonc** [comment]
@myflashlab I replied directly to the email you sent me a few days ago. I can send the information again through here if you need me to.

**Comment by myflashlab** [comment]
This is the last email I asked my colleague to send to you guys: 

> Awesome. I think we just spot the problem! on Some test purchases, Google is not sending over the OrderId! that's why the local db could not save the purchase properly. please replace the ANE with this one now: https://drive.google.com/open?id=0B7eHG2CEml2TN2dUYWZtZmo1WEU
This version should do the trick, if it's not, please send us the logs once again.

Maybe you didn't receive the new ANE. Anyway, please use this newer one.

**Comment by felipecgonc** [comment]
@myflashlab Oops sorry! I got it, it's just that I don't work on Wednesdays so I didn't see it earlier. I'll be sending you the logs right away.

**Comment by jankri** [comment]
@myflashlab the new version seems to work correctly. I see only really purchased items. I just sent you the logs for a reference. Thanks for good support.

**Comment by myflashlab** [comment]
Glad to hear that :) Thanks for your cooperation on helping us locate the problem. We will be cleaning the ANE and release a new version by tomorrow at most.
