### ISSUE TITLE
Error: Authentication is required. You need to sign in to your Google Account.

### ISSUE THREAD

**Issue by obuw** [myflashlab/inAppPayments-ANE#41]
Whenever I try to make a purchase that is not android.test.purchased, the test device gives this error:

> Error: Authentication is required. You need to sign in to your Google Account.

The app is rolled out as an alpha. My account is in the list of alpha testers. What am I doing wrong? Why is this so frustrating to test?

**Comment by myflashlab** [comment]
Such error messages are thrown from the native side and not the ANE side. Check some links here for example: https://www.google.com/search?q=%22Authentication+is+required.+You+need+to+sign+in+to+your+Google+Account%22+inappbilling&bav=on.2,or.r_cp.&biw=1280&bih=694&client=firefox-b-ab&ech=1&psi=JqBLWf2GHMj4wALB-5yYDw.1498128424320.3&ei=JqBLWf2GHMj4wALB-5yYDw&emsg=NCSR&noj=1&gfe_rd=cr

**Comment by obuw** [comment]
Thanks, I just noticed that the app was rejected due to supposed copyright infringement, so that is probably why the app was giving this error. (The fact that you have to *publish* your app to even test in-app purchases is beyond stupid, but that's just google for you...)

Anyway, thanks for the help. Hopefully I won't get any more problems once the publishing bs is sorted out.
