### ISSUE TITLE
The InAppPayments ANE doest not support Non-renewable subscription for iOS?

### ISSUE THREAD

**Issue by nxidea123** [myflashlab/inAppPayments-ANE#42]
My project must use  Non-renewable subscription, but ANE only support following type,
AUTO_RENEWAL
CONSUMABLE 
PERMANENT

how can i do?

**Comment by myflashlab** [comment]
They are basically the same. we kept them down to these 3 types to make sure the iOS side looks like the Android side. the difference is that Non-renewable subscriptions won't be renewed automatically and you should do that yourself. To do that, you should read the ```getPurchases``` and check the purchase time manually yourself.
