### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#43]
Everything was working fine list time I checked, but now I get this on app start:

ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at Function/<anonymous>()
	at Function/http://adobe.com/AS3/2006/builtin::apply()
	at SetIntervalTimer/onTimer()
	at flash.utils::Timer/_timerDispatch()
	at flash.utils::Timer/tick()

**Comment by polyGeek** [comment]
Note: error comes while debugging in simulator on Windows.
Using Flex16/AIR25.

**Comment by polyGeek** [comment]
I downloaded the ANE fresh from GIT and updated my lib. Now it doesn't crash on startup. However, I can't remember how I get the paid version of the ANE. Do I need to do anything else?

**Comment by myflashlab** [comment]
Please note that the ANE must be run on a real device not a simulator. And you can update your commercial version by logging into your myflashlabs panel.
