### ISSUE TITLE
Troubles with promo codes and restoring purchases

### ISSUE THREAD

**Issue by felipecgonc** [myflashlab/inAppPayments-ANE#44]
Hello,

I am encountering a great deal of trouble while trying to use promo codes to unlock content in my app on iOS. The thing is, after redeeming the code through the App Store app (there doesn't seem to be a way to do that during the purchase anymore, so I couldn't do it within my app), I am unable to restore the purchases (using the getPurchases() method and checking for the purchases array's length and content), though it seems this is probably caused by Apple's servers themselves. 

So, the solution I tried was checking whether the msg parameter returned by the doPayment() function was Billing.ALREADY_OWNED_ITEM and restoring the purchase internally. When trying to buy the item after redeeming the code in the App Store, a dialog box was shown saying something along the lines of "this item has already been bought and will be restored for free" but the code after the msg check was not triggered. Trying to restore purchases after that is useless too.

Now, all of this testing has been done on distribution versions available on the App Store, since doing this with a development provisioning profile in testing mode only gives me access to the Sandbox environment, so I understand this is extra complicated. But I can't keep waiting for Apple's 3 day approval process every time I make a change for testing on my app, so I'd like to ask:

First of all, am I doing this right in terms of using promo codes and restoring them within the app? And secondly, what is the probability of there being an error with the ANE (having to do with the Billing.ALREADY_OWNED_ITEM msg not being sent or something)? Some help would be appreciated.

Thnaks in advance!

**Comment by myflashlab** [comment]
promo codes are usually used for paid apps if I'm not wrong, but anyhow, it seems like the problem is within the iOS itself because I searched a lot and couldn't find an answer. I did find the same question though with no answer, like this one: https://forums.developer.apple.com/thread/67387 We try to search more on this. If you could find an answer, please share that with us also.

**Comment by myflashlab** [comment]
It seems like promotional codes can also happen on the Android side. we are going to investigate this in details and will update this issue... https://github.com/myflashlab/inAppPayments-ANE/issues/46
