### ISSUE TITLE
iOS & Android purchases made outside of the app

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#46]
Do you have a recommended way to handle Apple's option to make purchases outside the app?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
