### ISSUE TITLE
getPurchases DOES returns Consumable products

### ISSUE THREAD

**Issue by gilamran** [myflashlab/inAppPayments-ANE#48]
According to the documentation: when running `getPurchases` should will never get consumable products. But we do get them.
Actually this is very useful, so on startup we check for `getPurchases`, and any product that was not consumed, do `forceConsume` it.

How to reproduce:
Buy a consumable product, and when you see the "Payment success" (From Google), shutdown the app. re-start the app, and call `getPurchases`, you will see the consumable product there.

My question is, can I count of that?
If the above situation happened to one of my users (Internet drop on purchase, or anything that this product was not consumed), I can `forceConsume` it on startup.

If there are any other/better ways to handle miss-consumed products I would love to know about them. I don't want my users angry :-)
Thanks!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
