### ISSUE TITLE
androidSupport.ane size

### ISSUE THREAD

**Issue by gilamran** [myflashlab/inAppPayments-ANE#49]
Hi,
When trying to use the `inAppPurchase.ane` we also must include the `androidSupport.ane` which is 6Meg+.
This will raise the size of our app considerably. Is there any way to avoid it, or even parts of it to reduce its size?

On Version 2.0.0, the ANE was only 242K

Thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
