### ISSUE TITLE
i was tested in ios and successfully get the product list. once i click purchase and return "this item not found on google or apple store", why?

### ISSUE THREAD

**Issue by terryteo321** [myflashlab/inAppPayments-ANE#50]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version:
* iOS Version:
* AIR SDK Version:

## Problem Description ##
Describe your problem in detail.
* Copy your manifest ```.xml``` file.
```xml
<my><manifest/></my>
```
* Copy your Actionscript code.
```actionscript
var myScript:AS;
```

## Steps to Reproduce ##
Tell us how this issue can be reproduced.

## Known Workarounds ##
Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
