### ISSUE TITLE
Info on undocumented features (i.e. Billing.ANDROID_MARKET = Billing.MARKET_GOOGLE).

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/inAppPayments-ANE#51]
Implementing the ANE I was looking at your sample project.
One line triggered my attention:
Billing.ANDROID_MARKET = Billing.MARKET_GOOGLE;

Apparently, as reported by the IDE, there is one variable:
Billing.ANDROID_MARKET

And 3 constants:
Billing.MARKET_GOOGLE
Billing.MARKET_CAFEBAZAAR
Billing.MARKET_AMAZON

This is undocumented in ASDocs, and I can't find any reference to these. What are they used for? Are they necessary?

Thank you

**Comment by myflashlab** [comment]
Nice catch :) But no, you can simply ignore them. They are there for our future tests. ```Billing.MARKET_GOOGLE``` is set by default so you don't need to call that at all.

**Comment by PippoApps** [comment]
Thank you :)
