### ISSUE TITLE
Android "No Product Match Found on Server!"

### ISSUE THREAD

**Issue by xangel82** [myflashlab/inAppPayments-ANE#53]
## Environment ##
* Android API Version: 26.0
* AIR SDK Version: Flex 4.16.0 

## Problem Description ##
I integrated the ANE in the my application and I receive the message "No Product Match Found on Server!"

	Billing.init(PUBLIC_KEY, 
				[	// Android product IDs which you have already set in your Google Play console.
				"ads06", 
				"ads12"
				], 
				null, 
				onInitResult);

OnInitResult I received 0 and MSG:  "No Product Match Found on Server!"

I config all Subscriptions (Not like Managed Product but subscription) in the Developer Console, with the same name in the code ("ads06", "ads12"), they are actives and deployed two days ago. 

I checked many times the Public Key, it's correct, I took it from Developer Console -> App dashboard -> Service & Api -> Licenses and billing in-app.

I released in the Alpha Test, with flag debug true and false, I added an different test account, but when I open the application i received the same error message.

The internet connection for the app is ok.

InAppPayments ANE is compatible with the subscriptions? 

The Libs are:
1) InAppPayments.swc
2) permissionCheck.swc
3) InAppPayments.ane
4) permissionCheck.ane
5) androidSupport-full.ane
6) overrideAir.ane

Thanks

**Comment by myflashlab** [comment]
There could be many reasons why you see this error. Have you checked similar issues? https://github.com/myflashlab/inAppPayments-ANE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20No%20Product%20Match%20Found

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
