### ISSUE TITLE
androidSupport ane could not be found

### ISSUE THREAD

**Issue by polyGeek** [myflashlab/inAppPayments-ANE#54]
I've had this happen at last two times before. I can never find the docs to fix this without posting the question again.

Here's the error message I get when trying to export for Android:

Error occurred while packaging the application:

aapt tool failed:warning: string 'auth_client_needs_enabling_title' has no default translation.

warning: string 'auth_client_needs_installation_title' has no default translation.

warning: string 'auth_client_needs_update_title' has no default translation.

warning: string 'auth_client_play_services_err_notification_msg' has no default translation.

warning: string 'auth_client_requested_by_msg' has no default translation.

warning: string 'auth_client_using_bad_version_title' has no default translation.

Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.

Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.

Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.

Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.

C:\Users\danfl\AppData\Local\Temp\141855c4-64e8-4470-a249-b3aff85010c0\res\values\wallet_attrs.xml:7: error: Attribute "theme" already defined with incompatible format.

C:\Users\danfl\AppData\Local\Temp\141855c4-64e8-4470-a249-b3aff85010c0\android.support.v7.appcompat-res\values\values.xml:189: Original attribute defined here.

Also, how do I go about making sure I have the latest versions off all the in-app payment and androidsupport ANEs? 

Cheers

**Comment by myflashlab** [comment]
Are you sure you are using the latest version of AdobeAIR? Will you please post your manifest .xml file here?


> how do I go about making sure I have the latest versions off all the in-app payment and androidsupport ANEs?

All our ANEs have a .VERSION property which you can call and see the version number.

**Comment by polyGeek** [comment]
First, thanks so much for responding. I really appreciate your support in
helping me get this ironed out. All of this was working before, and was
deployed in a version of the app in stores now. But, something changed with
the properties settings and it's all screwy now.

Billing.VERSION = 2.2.0

I don't know if there's any way for me to find out what version of
the androidSupport.ane I'm using.

There is no corresponding androidSupport.swf, correct? All of the ather ANE
files that I use have both a .ane and .swf.

Attached is the RunPee-app.xml file. Is that what you need to see? I also
have screenshots of my properties screens. These settings allow me to test
in the simulator, but not on the device.

Here's what I would like: do you have the instructions for getting the
latest versions of all the ANEs and adding them to a project? And, is it
possible to set up a project so that I can test in the desktop simulator,
and then switch to testing on the devise, without changing property
settings?

When I include the inapppayments.ane/swf I get the following error when
trying to build a debug version on the device.




Error occurred while packaging the application:


aapt tool failed:warning: string 'auth_client_needs_enabling_title' has no
default translation.
warning: string 'auth_client_needs_installation_title' has no default
translation.
warning: string 'auth_client_needs_update_title' has no default translation.
warning: string 'auth_client_play_services_err_notification_msg' has no
default translation.
warning: string 'auth_client_requested_by_msg' has no default translation.
warning: string 'auth_client_using_bad_version_title' has no default
translation.
Warning: AndroidManifest.xml already defines versionCode (in
http://schemas.android.com/apk/res/android); using existing value in
manifest.
Warning: AndroidManifest.xml already defines versionName (in
http://schemas.android.com/apk/res/android); using existing value in
manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in
http://schemas.android.com/apk/res/android); using existing value in
manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in
http://schemas.android.com/apk/res/android); using existing value in
manifest.
C:\Users\danfl\AppData\Local\Temp\9c1210f5-48aa-4f96-8b0f-
e7d577d66821\res\values\wallet_attrs.xml:7: error: Attribute "theme"
already defined with incompatible format.
C:\Users\danfl\AppData\Local\Temp\9c1210f5-48aa-4f96-8b0f-
e7d577d66821\android.support.v7.appcompat-res\values\values.xml:189:
Original attribute defined here.

**Comment by polyGeek** [comment]
Hi, just checking if you guys got the above response? Help please. 

Can I have the instructions and files that someone who just downloaded the ANE would get? I'll just start over from scratch and try to make this work.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
