### ISSUE TITLE
Support Promoted IAP API for iOS 11

### ISSUE THREAD

**Issue by sjabberwocky** [myflashlab/inAppPayments-ANE#55]
Hi!
With iOS 11 Apple introduced Promoted IAP API, which allow to buy IAP from AppStore.
This feature is highly needed for new f2p apps.
Could you add it?
Link with more details - https://developer.apple.com/app-store/promoting-in-app-purchases/

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
