### ISSUE TITLE
getPurchases not returning any purchases, but when trying to purchase the product, the system returns "This item is already purchased".

### ISSUE THREAD

**Issue by obuw** [myflashlab/inAppPayments-ANE#56]
As the title says, getPurchases returns an empty array, but if I try to purchase a product, the system returns the message "This item is already purchased, you should let user use this item.".

I am not using forceConsume anywhere. The product is not treated as a consumable. I am relying on the getPurchases method to know the purchase date of the products. So if it does not work, that means my customers' purchases are no longer accessible which is a pretty big issue!

Is this by any chance because the app is in the beta stage, and not production?

Oh, and what does the Billing.IS_DEBUG_MODE parameter do? I have it turned off (set to false).

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
