### ISSUE TITLE
Can't get the IOS purchase receipt?

### ISSUE THREAD

**Issue by burnside** [myflashlab/inAppPayments-ANE#57]
I can't figure out how to get the base64 encoded purchase receipt of an iOS purchase transaction.

eg from the milkman plugin: 

https://www.milkmanplugins.com/as3doc/storekit/com/milkmangames/nativeextensions/ios/StoreKit.html#getAppReceipt()

I need it to validate purchases...

https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

**Comment by PippoApps** [comment]
This is a club membership request, it would be great if we can go through this asap.

**Comment by PippoApps** [comment]
As from your code, this is what we get back on a successful transaction on iOS:

**Comment by myflashlab** [comment]
iOS transactions is not currently returned in our ANE. Guys, we are working on a huge update on all our ANEs and we have to finish our to-do list (which includes billing iOS receipts too) in a ~one month margine. we are doing everything we can to have it till mid January. FYI: before 2018 starts, all dependencies and Firebase collection will be updated and right after that, other ANEs will have new features including the billing ANE... stay alert...

**Comment by PippoApps** [comment]
Ok thank you. I understand, my bad I didn't check throughly for this particular feature before we purchased. Cheers.

**Comment by myflashlab** [comment]
we're working on it at the moment... new version should be ready soon. :)

**Comment by burnside** [comment]
Thank you!  What is your expected ETA?

**Comment by myflashlab** [comment]
early next week is when we are expecting the new release... we'll keep you updated.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
