### ISSUE TITLE
getPurchases not returning anything on released app

### ISSUE THREAD

**Issue by obuw** [myflashlab/inAppPayments-ANE#58]
We have released a new app yesterday on android, but it's getting stuck on the billing initialization!

All local builds are working, but the google play store version does NOT! This is extremely frustrating because we can't figure out what the error is, as the issue can't be replicated on builds that are not from the play store.

Is this some kind of licensing issue? Do we need to enter our account details somewhere? Something special we need to do for production builds?

**Comment by myflashlab** [comment]
please send us a link to your app so we can have a look see... if you wish to keep the app link a secret, please email it to us https://www.myflashlabs.com/contact/

**Comment by obuw** [comment]
I've just sent an email with the app name.

**Comment by obuw** [comment]
Ok, I was now able to replicate an issue on a debug build. It doesn't seem to be related to the ANE, sorry!

Thanks for the help, I'll take it from here.

**Comment by obuw** [comment]
Ok, I'm re-opening the issue with an edited title as it is no longer urgent.

It *is* related to the ANE after all. The ANE does initialize, but the server never responds to the getPurchases call. I get these outputs:

-swc-Billing- _os = android
-swc-PurchaseDB- _file = /data/user/0/~~~~/~~~~/Local Store/com.myflashlab.air.extensions.billing/purchasData4.db
Billing Initialized
-swc-Launcher- getPurchases 1.2
-swc-Launcher- getPurchases 1.3

Even when it did work, getPurchases was not actually returning the purchases properly (opened another issue about that earlier), so I have disabled that part of the app completely now. But I wanted to re-open the issue here so you can investigate why getPurchases does not work sometimes.

**Comment by myflashlab** [comment]
1. which version of the ANE are you using? I presume, you're using V2.2.2, correct? 
2. which version of AndroidSupport and overrideAIR are you using?
2. please activate the ANE debugger as follow and send us more logs being returned by that:

Add this before any ANE is initialized:
```actionscript
OverrideAir.enableDebugger(myDebuggerDelegate);
function myDebuggerDelegate($ane:String, $class:String, $msg:String):void
{
	trace("["+$ane+"-"+$class+"]"+$msg);
}
```

**Comment by obuw** [comment]
I'm using Billing 2.2.0, AndroidSupport 24.2.2, OverrideAIR 4.0.0. Exporting for AIR 26.0. 

I will update and see if that makes a difference. Then I will activate the debugger and send you more logs.

By the way do I also need to set Billing.IS_DEBUG_MODE = true ? I have no idea what that does.

**Comment by myflashlab** [comment]
Yes, make sure to update them all. the latest version has fixed a lot of things!
 
```Billing.IS_DEBUG_MODE``` must be true when you are testing your app. when releasing in GooglePlay, you must set it to false surely.

**Comment by Adrian-S** [comment]
Seams a lot of people get this issue when publishing. Usually all of us get at this step where we try an publish, and forget one small step. A publish checklist would help a lot.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
