### ISSUE TITLE
Android: Billing.forceConsume(itemId, onForceConsumeResult); - callback doesn't fire

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/inAppPayments-ANE#60]
I am trying to consume consumable product that I purchased.
I using test order.
Result: callback doesn't fire

**Comment by myflashlab** [comment]
And do you receive any error logs from AndroidStudio logcat?

**Comment by CrazyFlasher** [comment]
no, no errors.
May it be so, that the consumable item on Android is being automatically consumed after purchase by the lib? Cause I also do not receive it in the list of items `Billing.getPurchases(onGetPurchasesResult);`

**Comment by myflashlab** [comment]
When calling the ```Billing.doPayment```, are you setting the first parameter as ```BillingType.CONSUMABLE```?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
