### ISSUE TITLE
Is AIR namespace 28 Beta really the minimum?

### ISSUE THREAD

**Issue by perholmes** [myflashlab/inAppPayments-ANE#61]
Hi,

I'm prevented from even testing the billing API, because you've built the latest release against AIR 28 beta. It's a HUGE risk for us to update AIR, and we only do it when we have to.

I'm interested in trying your ANE because there's a bug in the MilkmanGames iOS StoreKit where the app receipt is always null. I'd switch to your ANE in a heartbeat if it works there, but I'm suddenly risking torpedoing the project by messing with the AIR installation, which is not trivial, and we have Flex components as well that we'd get rid of if we could.

Is there any reason in the whole world why your ANE can only run against the very latest AIR BETA? Isn't that a ridiculously strict requirement that drops a bomb on most users?

Per

**Comment by perholmes** [comment]
Hi,

I've solved my issue with the Milkman Games iOS StoreKit, it's actually a bug in Flash Builder. My receipt was there all along, but when printing it to the log with trace(e.receipt);, the live debug log itself is buggy and shows this as blank lines that inexplicably contain the Base64 receipt when you copy/paste the blank spaces out into a text editor.

Per

**Comment by perholmes** [comment]
But no answer on the minimum AIR version? You're requiring people to compile against the latest BETA (not even release). That is a nasty requirement that I feel you ought to address.

**Comment by myflashlab** [comment]
AIR SDK 28 is not in BETA anymore http://www.adobe.com/devnet/air/air-sdk-download.html
New features we added to the ANE on the iOS side needs AIR 28. If you don't need them, you can keep using the older versions of the ANE. However, we are moving forward, AIR is also moving forward, it may be hard but you also should move forward with upgrading your app to the latest versions.
