### ISSUE TITLE
we have purchase inAppPayment ANE but it doesnt work very poor even we sent a email to customer support team but they not helping us....  Want to ask question to "myflashlabs" team if you not provide good quality service product or help you should dont right to selling bad product... it was our mistake we select ATM myflashlabs ANE... we strongly recommend https://www.milkmanplugins.com/air-native-extensions great work + great help always....  regards ~ Saif

### ISSUE THREAD

**Issue by usmanredsoft** [myflashlab/inAppPayments-ANE#64]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version:
* iOS Version:
* AIR SDK Version:

## Problem Description ##
Describe your problem in detail.
* Copy your manifest ```.xml``` file.
```xml
<my><manifest/></my>
```
* Copy your Actionscript code.
```actionscript
var myScript:AS;
```

## Steps to Reproduce ##
Tell us how this issue can be reproduced.

## Known Workarounds ##
Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by usmanredsoft** [comment]
we have purchase inAppPayment ANE but it doesnt work very poor even we sent a email to customer support team but they not helping us....

Want to ask question to "myflashlabs" team if you not provide good quality service product or help you should dont right to selling bad product... it was our mistake we select ATM myflashlabs ANE... we strongly recommend https://www.milkmanplugins.com/air-native-extensions great work + great help always....

regards
~ Saif

**Comment by myflashlab** [comment]
Thanks for your email. I’ve seen them and will check it out a.s.a.p however, you do realize that it’s an international holiday, right? It’s mother’s day. I don’t appreciate you suggesting that we are providing poor ANEs! 

1) we are humans and we are off work on weekends and holidays.

2) we have email support for club members and GitHub support for ordinary individual purchases.

3) there are demo versions of our ANEs free to access on GitHub so everyone can test before a purchase.

4) we have the ANELAB software to help devs implements ANEs easier.

5) the first thing that a programmer needs is patience!
