### ISSUE TITLE
Can't get the ANDROID purchase Signature?

### ISSUE THREAD

**Issue by lamltsandinh** [myflashlab/inAppPayments-ANE#66]
## Environment ##
* Android API Version:  24
* AIR SDK Version: 29
* AIR inAPp Version:2.3.0

## Problem Description ##
i see OverAir show log 
```
ONVERAIR [IN_APP_BILLING-AirCommand]purchase != null, getSignature() = MaUCH9mYMvYn7sml/sxKVlvsbT+yiIAr0pdNGuNeM/4eaeeE7/526kYfeExKESayRfivjtWFBpiCkSewwY0EDjI1JSOJZBKJjCPnpDinnXNK/Mvrhj8bgpdq+oDwpNfE1B1XlyIOM+RLuR4QOxKDuxAuz6oa1K/3cP7lEtXVxIQ0jjxow0rAnrvFAkLlP5gUc4/w3hB4378+mTfMaBBLT3AaLzO5ny5h6mePUjMLfhbyW8RBPrS4UXQ9zZyXKPHrlc6VDi/81VvlypKAQplgovvMZmouIGceX4MCi6ob6godj2EQTLcZYfbU/B0V0LGYNeSx5ai6fkozln+Lf4ZZiA==_currBillingType = 1
``` 
after onPurchaseFinished but,I have not received signature in data

```actionscript
$data.billingType = 1
$data.orderId = GPA.3309-8320-1486-20972
$data.developerPayload = null
$data.productId = 21
$data.purchaseState = 0
$data.purchaseTime = 1523609889825
$data.purchaseToken = ncfcejhopbebjififgdkhlda.AO-J1Oz72dzxwbRx6rlfwUtsxn9bJRIDFlY30bL9T0xBF-2ns-nyiDdaf4XfLBPp_W5AhYu85cNdJbXbDgz_6vIS0INpxOAD6KpIu1twMRRbVa0wXBLS4nE
$data = [object Purchase]
$data.autoRenewing = false
$data.signature = null
```

**Comment by truongnx9218** [comment]
I have same issue. Help me :(

**Comment by myflashlab** [comment]
Ok, this problem should be fixed now. please replace the current ANE with this one and check again.
[inAppPayments.ane.zip](https://github.com/myflashlab/inAppPayments-ANE/files/1987081/inAppPayments.ane.zip)

if the signature is still not returned, please send us the complete OverrideAIR logs so we can better understand what the problem could be. Thanks.

**Comment by ikuprin** [comment]
Has released version 2.5.0 this fix?

**Comment by myflashlab** [comment]
@ikuprin yes, it should be. Please let us know if you are experiencing otherwise.

**Comment by myflashlab** [comment]
not at all, feel free to ask. https://github.com/myflashlab/inAppPayments-ANE/tree/master/AIR/lib

**Comment by ikuprin** [comment]
Maybe I do smth wrong, but downloaded ane from link is demo.

**Comment by myflashlab** [comment]
Well, you asked for the demo version :) that’s the link. Get the commercial version from the club package or ANELAB if you are a club member. Or the package you can download after the purchase.

**Comment by ikuprin** [comment]
Fuf. Finally found how it works: https://www.myflashlabs.com/my-account/downloads/

Sorry for disturbing.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
