### ISSUE TITLE
Billing on iOS works ONLY if initialized in app constructor. Useless for in-app purchases.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/inAppPayments-ANE#69]
Billing has everything, callbacks AND product IDs initialized together.
As for the model you described me in another ticket, callbacks must be initialized in constructor on iOS. But this means shop items must be hardcoded in app (how else otherwise they could be retrieved?).
This doesn't make sense for a marketable app, since purchasable items do change in time.
Since in another ticket you have wrote to me I could initialize Billing afterwards, I spent some hors debugging elsewhere, then I tried then moving initialisation on constructor, and bang, it works (GRUNT).

**Please split callbacks initialization and purchasable item IDs setup or this ANE will be useless in most cases**

**Comment by myflashlab** [comment]
Oh, you are correct, this has been a requirement for the very latest version of the ANE which has added support for iOS 11+ promo purchases through app store. We will fix it a.s.a.p. Thanks for bringing this up.

**Comment by myflashlab** [comment]
First, replace the ANE with this new version: [inAppPayments.ane.zip](https://github.com/myflashlab/inAppPayments-ANE/files/1987081/inAppPayments.ane.zip) This will fix the problem you have.

But there's something else wrong with iOS 11 in-app promo purchase feature thing, you see, the ANE must be initialized in app's constructor function for this feature to be able to work and we couldn't find another place for it.

And as you suggested, if the ANE is initializing so soon, how would it find time to download the product IDs from server. We couldn't find a solution for this and we didn't find anything on apple forums neither.

A workaround for someone who wants to use iOS 11 promo purchase feature and also wants to load the list of product IDs from server, could be to init the ANE first in the constructor function and when the list is loaded from server, you may dispose the ANE and re-init it with the new IDs! Haven't tested this, but seems to be a doable workaround. not pretty though!

**Comment by myflashlab** [comment]
in-app promo feature still works in the new ANE (if initialized in the constructor function). Otherwise, payments will work normally if the ANE is not initialized in the constructor. So, this should be fine for now.

**Comment by myflashlab** [comment]
Ok, just released the new version to ANELAB channel. The new version also fixed this bug #66

**Comment by PippoApps** [comment]
It works. Thanks
