### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by varadig** [myflashlab/inAppPayments-ANE#7]
[Fault] exception, information=ArgumentError: Error #3500: The extension context does not have a method with the name command.

**Comment by varadig** [comment]
I got this error on Billing.init, with custom project, and the sample too.

**Comment by varadig** [comment]
Another strange issue, the 
`private function onInitResult($status:int, $msg:String):void {`
is never triggered by 
Billing.init(googlePlayKey, googleProductsID, appleProductsID, onInitResult);`

**Comment by qdrj** [comment]
I've encountered the same issue.
I've wrapped Billing.init inside try block but it is still crashing on emulator while testing

**Comment by myflashlab** [comment]
You must run the ANE on a real device. Please follow the instructions on
the home page of the repository and make sure to watch the YouTube videos
we have linked from there.

On Monday, May 2, 2016, Vladislav Forsh <notifications@github.com> wrote:

> I've encountered the same issue.
> I've wrapped Billing.init inside try block but it is still crashing on
> emulator while testing
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/inAppPayments-ANE/issues/7#issuecomment-216257226>
>


-- 
Sent from iPhone

**Comment by qdrj** [comment]
Thanks for the fast reply.

I get it that we should test IAPs on real devices.

But the majority of times we run it on an emulator. So is there any way to detect if an app is running on the emulator and disable ANE? I was expecting that it is done internally inside ANE.

Thanks in advance!

**Comment by myflashlab** [comment]
unfortunately no. but you can always disable the ANE when testing in the emulator... I suppose just commenting the ANEs from the manifest .xml file would do the job.

**Comment by myflashlab** [comment]
please close the issue if you don't have more questions... Thanks.
