### ISSUE TITLE
Question: how to retrieve unprocessed purchase.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/inAppPayments-ANE#70]
Hi,
I have a doubt, if a purchase goes through, and let's say app crashes or device runs out of battery before purchase can be processed in app, how can this purchase be retrieved at next login?
Is this what local cache is needed for?
thank you

**Comment by myflashlab** [comment]
When ANE initializes, the native code will take care of such scenarios. the purchase dialog opens from where it's was left.

**Comment by PippoApps** [comment]
Fantastic, thank you. I ask you this since in my last experience with MilkMan I had to manage this manually.

**Comment by myflashlab** [comment]
Sure, if any trouble or anything, just let us know. As always, we try to make ANEs work better. If there's a bug, we surely like to kill it! :D

**Comment by PippoApps** [comment]
Thank you. I take advantage :) since there is no quit event on iOS, i call ANE clear local cache after a successful purchase. Do you guys think it could work?
