### ISSUE TITLE
Question:  Purchase.purchaseToken vs. Billing.iOSReceipt

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/inAppPayments-ANE#71]
Hi,
on Android we do validate on server retrieving the Purchase.purchaseToken from each successful purchase event.
How does the Billing.iOSReceipt apply? Since it does not seem to be related to the single Purchase?
Thank you

**Comment by myflashlab** [comment]
This post should help: https://github.com/myflashlab/inAppPayments-ANE/issues/72#issuecomment-389214181

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
