### ISSUE TITLE
Billing.iOSReceipt not enough for validate purchases on server side

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/inAppPayments-ANE#72]
Function onGetPurchasesResult get array of Purchase. I need to validate each purchase on server side, but I haven't receipts in each Purchase. Maybe better to create field with receipt into Purchase?

**Comment by myflashlab** [comment]
yeah, totally understand the pain. we have been asking ourselves this question a lot too. but that's just how iOS works. unlike Android, things on the iOS side are a bit harder to handle.

On the ANE side, we are garbing the receipt form the native side and hand it over to the AIR side. What you can do with the information form there is on your hand. read below for more info:

 https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

**Comment by ikuprin** [comment]
It's sounds not good. I'm migrate to your anes pack from Distriqt, because they very slow for updates. Your anes is beautifull, but InAppPayment brings a lot of pain... It's not ready for work with server-side verification of purchase.

Please, take a look for https://airnativeextensions.com/extension/com.distriqt.InAppBilling - there is restoring of not finished transactions, manual consuming of transaction and more useful functionality.

With hope for understanding,
Alex

**Comment by myflashlab** [comment]
Besides the auto-renewal ones, iOS products are either permanent or consumable when you create them on itunesconnect. I'm not sure if I am understanding your question correctly.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
