### ISSUE TITLE
How do I test for buying some items both android and ios?

### ISSUE THREAD

**Issue by tlearsakura** [myflashlab/inAppPayments-ANE#75]
## Environment ##
* Android API Version:
* iOS Version:
* AIR SDK Version: 29

## Problem Description ##
I build as .APK and I installed on android device. When I pressed buy button in my game, the dialog show message the developer cannot do this order something like that. I want to know how do I test it.
I want to get log message from "onGetPurchasesResult" function. Like these ,

log("----------------");
log("purchaseData.orderId = " + purchaseData.orderId);
log("purchaseData.productId = " + purchaseData.productId);
log("purchaseData.purchaseState = " + purchaseData.purchaseState);
log("purchaseData.purchaseTime = " + purchaseData.purchaseTime);
log("purchaseData.purchaseToken = " + purchaseData.purchaseToken);

and log from "onPurchaseResult" function. Like these,

log("$data.billingType = " + $data.billingType);
log("$data.orderId = " + $data.orderId);
log("$data.developerPayload = " + $data.developerPayload);
log("$data.productId = " + $data.productId);
log("$data.purchaseState = " + $data.purchaseState);
log("$data.purchaseTime = " + $data.purchaseTime);
log("$data.purchaseToken = " + $data.purchaseToken);

I want to know both android and ios. Thank you.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
