### ISSUE TITLE
subscription not returned in products list on Android

### ISSUE THREAD

**Issue by Samuramu** [myflashlab/inAppPayments-ANE#76]
I have a project that's been working ok for the last year or so, on recent updates we saw that subscriptions stopped. 
When I debug on device, I can see only PERMANENT products returned.
SUBSCRIPTION purchases are not returned.
On iOS it still works fine.
I also tried adding a new subscription product to check if maybe the original one is broken for some reason, they are both active on Google Play console, and yet I only get the permanent product as a result.
Any help on this issue will be greatly appreciated.

**Comment by myflashlab** [comment]
Well, our recent updates to the ANE have had nothing to do with the fetching process of products. probably you should look for the problem somewhere else?

**Comment by Samuramu** [comment]
If I upload an older version of app with older ane I get the full list of products.
I need the recent one though because I'm using you're firebase extensions.

**Comment by myflashlab** [comment]
please tell me which version exactly is working?

**Comment by Samuramu** [comment]
The version that's working is from 5 Aug 2017 - v2.2.2

**Comment by myflashlab** [comment]
Please this demo version and see if everything works fine? even try some purchases to make sure. as far as we've seen, it's fine. 
[inAppPayments.ane.zip](https://github.com/myflashlab/inAppPayments-ANE/files/2031518/inAppPayments.ane.zip)
let us know how this goes. Thanks.

**Comment by Samuramu** [comment]
Thanks, downloading now and will test asap.

**Comment by myflashlab** [comment]
good :) thanks for bringing this to our attention. If you are a club member, you can have access to the final ANE through the ANELAB software. If not, the new version should be released tomorrow or so.
