### ISSUE TITLE
Unable to load previously purchased products.

### ISSUE THREAD

**Issue by idzdigital** [myflashlab/inAppPayments-ANE#79]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* iOS Version: 11.4
* AIR SDK Version: 29.0.0.122

## Problem Description ##
Hello Myflashlabs Team,
Products are loaded with their proper prices. But we cant fetch the previously purchased receipts.
We tried "Billing.clearCache();" but the problem didn't solve.
However i visited github and found similar issue faced by sruthi87 (https://github.com/myflashlab/inAppPayments-ANE/issues/34). Issue seems to be closed by your end but is it resolved ?
Also you replied to her asking for a demo project . Should we send you a demo project ?

Thank You.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
