### ISSUE TITLE
auto login

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/inAppPayments-ANE#81]
how to get auto-login in gameservices

function inita():void
	{
	    notify("inita")
		var options:GSignInOptions = new GSignInOptions();
		options.gamesSignIn = true; 
		GSignIn.init(options);
		GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_SUCCESS, onSilentSigninSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_FAILURE, onSilentSigninFailure);
		GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSigninSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSigninFailure);
	
		var account:GAccount = GSignIn.signedInAccount;
		if(account)
		{
			initGames();
		}
		else
		{
			
			GSignIn.silentSignIn();
		}
		
	  addSignInBtn();
	}

//=========================================onSuccessfullInit =====================================================================
	function addSignInBtn():void
	{
		
			if(!GSignIn.signedInAccount) 
			{
				GSignIn.signin();
			}
			else
			{
				notify("You are already signed in!");
			}
		
	}
	 function onSilentSigninSuccess(e:GSignInEvents):void
	{
		notify("----------------");
		notify("onSilentSigninSuccess");
		initGames();
	}

	 function onSigninSuccess(e:GSignInEvents):void
	{
		
		notify("e.account.scopes: "+ e.account.scopes);
		notify("----------------");
		notify("onSigninSuccess");
		initGames();
	}
	
	 function onSigninFailure(e:GSignInEvents):void
	{
		notify("onSigninFailure: " + e.msg);
	}
	
	
	
	 function onSilentSigninFailure(e:GSignInEvents):void
	{
		/*
			check the meaning of failure code here:
			https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes
			https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes
		 */
		notify("onSilentSigninFailure: " + e.msg);
	}

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
