### ISSUE TITLE
In App Payments ANE failed to initiate as no product match

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/inAppPayments-ANE#82]
## Environment ##
* Android Version: 26
* AIR Version: 30.0

Hi,

I have IAPs working fine on iOS but now trying to get the same on Android.

The ANE is loading ok but I am unable not match the list of products I have.  To be clear I know the products work because my current version of the game, which is live on Google but uses a competitor ANE, does work ok.  Because I am moving across to myflashlabs for other reasons I want to get all my ANEs from one source and avoid conflicts.

I am passing in my products array and I have doubled checked these.  They are in the form com.domainname.productname and have come from my working code for the other ANE and also match the iOS ones.  For completeness I have also tried them in the form air.com.domainname.productname in case something was adding the air at the front.

I have double checked the google play key and it's correct.

I have published both versions of the app to Google Play as Alphas an I am of course downloading as a test user.

My traces on the init result show:
iStatus = 0;
init was successful = false;
init msg = No product match found on server;
Billing.products - null;

So based on the message it seems that the products I am putting in the array are simply not matching the products on the store, and this is causing the initiation to fail, but for the life of me I can't see why.  Is there any way to get back the array of products that are on the store so I can check how the store sees them (I could do that with the Milkman ANE which allowed me to debug easily).  Is there any other way to test what the cause of the failure is.

Thanks

Stephen

**Comment by myflashlab** [comment]
please enable [OverrideAir.enableDebugger()](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairenabledebugger) so we can see more logs. Then post the logs to see if we can go further with that.

**Comment by LeapingSwan** [comment]
Scratch that.  No sooner, did. I post that, having been looking for ages, I found na very small error in my product id (non capitalisation off one letter) and it's now initiating.

Sorry!

Thanks

Stephen

**Comment by myflashlab** [comment]
Anyhow, please do get used to the [OverrideAir.enableDebugger()](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairenabledebugger) tool and try to provide us with as much details as possible. We'd be always happy to help :)

**Comment by LeapingSwan** [comment]
Actually I do have it running all the time while in development.  That said where I am working today I can't get Adobe Scout to work for my Android device (some problem with the network) so can't see traces unless I direct them to an on device text box - which I had focused on the output from the Billing init result status and message.

Thanks

Stephen
