### ISSUE TITLE
BILLING permissions not staying on manifest when publishing APK

### ISSUE THREAD

**Issue by zillywininc** [myflashlab/inAppPayments-ANE#83]
## Environment ##
* Android Version:
* iOS Version:
* AIR Version: 30

## Problem Description ##

I'm using ANELAB to export the correct Manifest file, which contains the following permissions:
```
  <uses-permission android:name="com.android.vending.BILLING"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.BILLING"/>
  <uses-permission android:name="android.permission..BILLING"/>
  <application>
```

I'm not sure why there's a ..BILLING as well, but I don't think it will cause problems. The line:
`  <uses-permission android:name="com.android.vending.BILLING"/>`
Is certainly required by Google to make in-app products in the Developer's console. When I publish the APK on Animate CC to upload to the Developer's console it rewrites the manifest and removes this line and then it looks like this:

```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.BILLING"/>
<uses-permission android:name="android.permission..BILLING"/>
```

Then when I go to the console and upload the APK in the "in-app products" section I get the following message:

Your app doesn't have any in-app products yet. 
To add in-app products, you need to add the BILLING permission to your APK.
Upload a new APK

How can I include this line in my manifest without Adobe Animate removing it during the publishing process?
`  <uses-permission android:name="com.android.vending.BILLING"/>`

Any help would be greatly appreciated. Thanks

```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.ZillyWin</id>
  <versionNumber>1.0.09</versionNumber>
  <versionLabel></versionLabel>
  <filename>inapp-test</filename>
  <description/>
  <name>inapp-test</name>
  <copyright/>
  <initialWindow>
    <content>inapp-test.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients>
  </initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.BILLING"/>
<uses-permission android:name="android.permission..BILLING"/>
</manifest>]]></manifestAdditions>
  </android>
  
  
  
  
  
  
  
  
  
  
  
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
</application>

```
```actionscript
Example code from the project GitHub
```

## Steps to Reproduce ##
Publish the file as an APK via Animate and upload to the in-app purchases section of the Google Console

## Known Workarounds ##

**Comment by myflashlab** [comment]
AdobeAnimate always tries to modify the manifest automatically by default but in it’s settings, you have the option to turn that off. So make sure the Animate is set to manual so it no longer modifies the manifest. Then run ANELAB and re-run ANE installations to make sure everything is set correctly.

Note: why do you have “android.permission.BILLING” twice?

**Comment by zillywininc** [comment]
> Note: why do you have “android.permission.BILLING” twice?

Thank you - will try this. I have BILLING twice as ANELAB seems to add ..BILLING by mistake instead of .BILLING. While troubleshooting, I added .BILLING to see if that was the issue.

**Comment by zillywininc** [comment]
This seems to have worked. Animate Publish settings needed to be modified to manually mange permissions via manifest. Thanks!
