### ISSUE TITLE
Parental Gates when opening promoted in-app purchases from the App Store

### ISSUE THREAD

**Issue by hpeide** [myflashlab/inAppPayments-ANE#84]
## Environment ##
* iOS Version: 11 up
* AIR Version: 31.0.0.96

## Problem Description ##
We have an app for kids with promoted in-app purchases. And since iOS 11 we get rejected because when purchasing from app-store the in app purchase process is not behind Parental Gates.

https://developer.apple.com/documentation/storekit/in-app_purchase/testing_promoted_in-app_purchases

## Steps to Reproduce ##
1. Send an iMessage to your self with this link:
itms-services://?action=purchaseIntent&bundleId=com.example.app&productIdentifier=product_name
2. Klikk the link from Messages.
3. The link opens the app and immediately starts the purchase process.

## Wanted behaviour ##
Before the purchase process is initiated Apple wants us to show Parental Gates and then start the purchase. Is this achievable?

**Comment by myflashlab** [comment]
This is a very nice feature and we will add it to the ANE in our next release. This should be available to you in mid/late November. cheers.
