### ISSUE TITLE
Error connecting the server

### ISSUE THREAD

**Issue by bajasim** [myflashlab/inAppPayments-ANE#85]
## Environment ##
* iOS Version: 10.3.3
* AIR Version: 31.0.0.96

## Problem Description ##
I have just downloaded your ANE library and demo and tested on an iPad. I am debugging in device via USB to an iPad.

App starts correctly, it reads the product information of all items added to the demo code and show the data as it is setup in my iTunesconnect account.
However when clicking on **getPurchases** or **purchase** buttons I received the following messages:

**purchase was succesful? false
purchase result message = Error connecting to server!**

And nothing happens.

Any help?

**Comment by myflashlab** [comment]
There could be many reasons! show us some logs, some codes! 

FYI: for more logs from inside ANEs, [read this](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairenabledebugger).

**Comment by bajasim** [comment]
Hi,

At the end it was a corrupt certificate from the appstore, it is solved
now, your ANE works fine.
Thank you for your prompt answer
